import { Inter } from 'next/font/google'
import './globals.css'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { CssBaseline } from '@mui/material';
import Navbar from './_lib/components/ui/navbar';
import Theme from './_lib/components/ui/theme';
import { getSession } from '@/auth';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: {
        template: '%s - Admin Console',
        default: 'Admin Console'
    },
    description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
    const session = await getSession();

    return (
        <html lang="en">
            <body className={inter.className}>
                <AppRouterCacheProvider>
                    <Theme>
                        <CssBaseline />
                        <Navbar session={session}>
                            {children}
                            <div id="modal-root" />
                        </Navbar>
                    </Theme>
                </AppRouterCacheProvider>
            </body>
        </html>
    )
}
