import { Inter } from 'next/font/google'
import './globals.css'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { CssBaseline } from '@mui/material';
import Navbar from './ui/Navbar';
import Theme from './ui/Theme/Theme';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'User Management',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AppRouterCacheProvider>
                    <Theme>
                        <CssBaseline />
                        <Navbar>
                            {children}
                        </Navbar>
                    </Theme>
                </AppRouterCacheProvider>
            </body>
        </html>
    )
}
