import { Inter } from 'next/font/google'
import './globals.css'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { CssBaseline } from '@mui/material';
import Navbar from './_lib/ui/Navbar';
import Theme from './_lib/ui/Theme';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: {
        template: '%s - Admin Console',
        default: 'Admin Console'
    },
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AppRouterCacheProvider>
                    <Theme>
                        <CssBaseline />
                        <Navbar>
                            {children}
                        </Navbar>
                    </Theme>
                </AppRouterCacheProvider>
            </body>
        </html>
    )
}
